/*
 * Copyright (C) 2021 jhendl
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/* 
 * File:   Renderer.h
 * Author: jhendl
 *
 * Created on February 7, 2021, 11:28 AM
 */

#pragma once

namespace vk
{
  class SurfaceKHR ;
}

namespace nyx
{
  /**
   */
  enum class ImageFormat : unsigned ;
  
  /**
   */
  enum class PipelineStage : unsigned ;

  /**
   */
  class Viewport ;
  
  template<typename Framework>
  class Image ;
  
  /** Forward decleration so the template interface can access this object's functionality.
   */
  template<typename Impl, typename Type>
  class Array ;

  /**
   */
  template<typename Framework>
  class Renderer ;

  namespace vkg
  {
    using Surface = vk::SurfaceKHR ;

    class Vulkan     ;
    class Buffer     ;
    class Image      ;
    class Renderer   ;
    class Pipeline   ;
    class Chain      ;
    class RenderPass ;
    class Descriptor ;
    
    /* Forward declared implmentation.
     */
    class RendererImpl ;
    
    class RendererImpl
    {
      private:
        friend class Renderer ;
        
        template<typename Format, typename ... Formats>
        friend void addFormat( RendererImpl& impl, Format format, Formats ... formats ) ;
        
        template<typename Format>
        friend void addFormat( RendererImpl& impl, Format format ) ;

        /** Default constructor.
         */
        RendererImpl() ;
        
        /** Default deconstructor.
         */
        ~RendererImpl() ;

        /** Method to add a viewport to this renderer.
         * @param viewport The viewport to add in the output of this renderer.
         */
        void addViewport( const nyx::Viewport& viewport ) ;

        /** Method to initialize this object.
         * @param device The device to use for all GPU operations.
         * @param nyx_file_path The path to the .nyx file on the filesystem to use.
         */
        void initialize( unsigned device, const vkg::RenderPass& pass, const char* nyx_file_path ) ;
  
        /** Method to initialize this object.
         * @param device The device to use for all GPU operations.
         * @param nyx_file_bytes The bytes of the .nyx file to use for this object.
         * @param size The size of the bytes array.
         */
        void initialize( unsigned device, const vkg::RenderPass& pass, const unsigned char* nyx_file_bytes, unsigned size ) ;
  
        /** Method to bind an array to one of this object's values on the GPU.
         * @param name The name associated with the value in the inputted pipeline.
         * @param buffer The vkg buffer to bind.
         * @param element_size The size of each element.
         * @param count The amount of elements.
         */
        void bind( const char* name, const nyx::vkg::Buffer& buffer ) ;
        
        /** Method to bind an image to one of this object's values on the GPU.
         * @param name The name associated with the value in the inputted pipeline.
         * @param image The vkg image to bind.
         */
        void bind( const char* name, const nyx::vkg::Image& image ) ;
        
        /** Method to retrieve the number of framebuffers generated by this renderer.
         * @return The number of framebuffers generated by this renderer.
         */
        unsigned count() const ;
        
        /** Method to retrieve the current framebuffer of this object that is to be drawn to next.
         * @return The index of the current framebuffer that is being drawn to next by this object.
         */
        unsigned current() const ;
  
        /** Method to retrieve the device used by this renderer.
         * @return Const reference to the device used for this renderer.
         */
        unsigned device() const ;
        
        /** Base method to use a buffer as vertices to draw.
         * @param buffer The buffer to use for vertices.
         * @param count The amount of vertices in the buffer.
         * @param offset The offset of the buffer to start at.
         */
        void drawBase( const nyx::vkg::Buffer& buffer, unsigned count, unsigned offset = 0 ) ;\
        void drawIndexedBase( const nyx::vkg::Buffer& index, const nyx::vkg::Buffer& vert, unsigned index_count, unsigned vert_count, unsigned offset = 0 ) ;
        
        /** Method to retrieve the format of the specified attachment index.
         * @param index The index of attachment to retrieve the format of.
         */
        nyx::ImageFormat format( unsigned index = 0 ) const ;

        /** Method to retrieve a framebuffer from this object.
         * @param index The index of framebuffer to retrieve. See @count for the amount.
         * @return Const reference to this object's internal framebuffer.
         */
        const vkg::Image& image( unsigned index = 0 ) const ;

        /** Base method to use a buffer as vertices to draw.
         * @param index The buffer to use for indices.
         * @param vert The buffer to use for vertices.
         * @param index_count The amount of indices in the buffer.
         * @param vert_count The amount of vertices in the buffer.
         * @param offset The offset of the buffer to start at.
         */

        /** Private method for pushing a value as a push-constant to this command buffer.
         * @param value The pointer value to push onto the Device.
         * @param byte_size The size in bytes of the object being pushed.
         * @param stage_flags The stage that the push constant is used on.
         */
        void pushConstantBase( const void* value, unsigned byte_size, nyx::PipelineStage stage_flags ) ;

        /** Method to reset this object and deallocate all allocated data.
         */
        void reset() ;
        
        /** Method to finalize this renderer's operations. Actually performs the recorded operations.
         * @note If this renderer has the context when initialized, this presents to the input window as well.
         */
        void finalize() ;

        /** Forward-declared structure to contain this object's internal data.
         */
        struct RendererData* renderer_data ;
        
        /** Method to retrieve a reference to this object's internal data.
         * @return Reference to this object's internal data.
         */
        RendererData& data() ;
        
        /** Method to retrieve a const-reference to this object's internal data.
         * @return Const-reference to this object's internal data.
         */
        const RendererData& data() const ;
    };

    class Renderer
    {
      private:
        
        /** Friend decleration so the template interface can access this object's functionality.
         */
        template<typename Framework>
        friend class nyx::Renderer ;
        
        friend class Chain ;
        
        /** Default constructor.
         */
        Renderer() = default ;
  
        /** Default deconstructor.
         */
        ~Renderer() = default ;
  
        /** Method to initialize this object.
         * @param device The device to use for all GPU operations.
         * @param nyx_file_path The path to the .nyx file on the filesystem to use.
         */
        void initialize( unsigned device, const vkg::RenderPass& pass, const char* nyx_file_path ) ;
  
        /** Method to initialize this object.
         * @param device The device to use for all GPU operations.
         * @param nyx_file_bytes The bytes of the .nyx file to use for this object.
         * @param size The size of the byte array.
         */
        void initialize( unsigned device, const vkg::RenderPass& pass, const unsigned char* nyx_file_bytes, unsigned size ) ;
  
        bool initialized() const ;
        /** Method to add a viewport to this renderer.
         * @param viewport The viewport to add in the output of this renderer.
         */
        void addViewport( const nyx::Viewport& viewport ) ;
        
        /** Method to bind an array to one of this object's values on the GPU.
         * @param name The name associated with the value in the inputted pipeline.
         * @param array The GPU array to bind to the pipeline variable.
         */
        template<typename Type>
        void bind( const char* name, const nyx::Array<vkg::Vulkan, Type>& array ) ;
        
        /** Method to bind an image to one of this object's values on the GPU.
         * @param name The name associated with the value in the inputted pipeline.
         * @param image The GPU image to bind to the pipeline variable.
         */
        void bind( const char* name, const vkg::Image& image ) ;
        
        /** Method to retrieve the device used by this renderer.
         * @return Const reference to the device used for this renderer.
         */
        unsigned device() const ;
        
        void setTestDepth( bool val ) ;
        void reset() ;
        const vkg::Descriptor& descriptor() const ;
        const vkg::Pipeline& pipeline() const ;
  
        /** The underlying implementation of this object.
         */
        RendererImpl impl ;
    };

    template<typename Type>
    void Renderer::bind( const char* name, const nyx::Array<vkg::Vulkan, Type>& array )
    {
      this->impl.bind( name, array ) ;
    }
  }
}


